services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - db-network
  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    ports:
      - "127.0.0.1:5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - postgres
    networks:
      - db-network
  app:
    container_name: app
    image: poster:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:8080"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/poster
    networks:
      - db-network
    depends_on:
      - postgres
volumes:
  postgresql:
    driver: local
networks:
  db-network:
    driver: bridge
